version: 0.2

phases:
  install:
    commands:
      - sudo yum -y update
      - sudo yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      - sudo yum -y install https://rpms.remirepo.net/enterprise/remi-release-7.rpm 
      - sudo yum makecache
      - sudo yum -y install yum-utils
      - sudo  amazon-linux-extras | grep php
      - sudo yum-config-manager --disable 'remi-php*'
      - sudo amazon-linux-extras enable php8.0 
      - sudo yum clean metadata
      - sudo yum install php-pear,php-cgi,php-pdo,php-common,php-curl,php-mbstring,php-gd,php-mysqlnd,php-gettext,php-bcmath,php-json,php-xml,php-fpm,php-intl,php-zip
      - echo "PHP Version ⬇"
      - php -v
      - echo "Initiation of build 🏠"
      - echo "Installing Composer 🎺"
      - curl -s https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - echo "Installing dependencies 📦"
      - composer install
      - echo "Installed dependencies 📦"

  build:
    commands:
      - echo "Building 🏗"
      - composer build
      - echo "Built 🏗"

  post_build:
    commands:
      - echo "Post build 🏗"
      - echo "Build completed on `date` 🏗"
