version: 0.2

phases:
  install:
    runtime-versions:
      docker: latest
    commands:
      - cat /etc/os-release
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo "Building 🏗"
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo "Built 🏗"
      - echo "PHP Version ⬇"
      - php -v
      - echo "Initiation of build 🏠"
      - echo "Installing Composer 🎺"
      - curl -s https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - echo "Installing dependencies 📦"
      - composer install
      - echo "Installed dependencies 📦"

  post_build:
    commands:
      - echo "Post build 🏗"
      - echo "Build completed on `date` 🏗"
