version: 0.2

phases:
  install:
    commands:
      - sudo yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      - sudo yum install -y https://rpms.remirepo.net/enterprise/remi-release-7.rpm
      - sudo yum-config-manager --enable remi-php80
      - sudo yum install php80
      - sudo yum install php-gd php-mbstring php-mysqlnd php-xml php-xmlrpc php-zip
      - echo "PHP Version ⬇"
      - php -v
      - echo "Initiation of build 🏠"
      - echo "Installing Composer 🎺"
      - curl -s https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - echo "Installing dependencies 📦"
      - composer install
      - echo "Installed dependencies 📦"

  build:
    commands:
      - echo "Building 🏗"
      - composer build
      - echo "Built 🏗"

  post_build:
    commands:
      - echo "Post build 🏗"
      - echo "Build completed on `date` 🏗"
